### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghost** [mist64/hvdos#1]
Hi
I cloned the code on my Mac and built it.
When I run './hvdos', it gives this error:
"Segmentation fault: 11"

OS X Version: 10.10
Clang++ version:
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix

**Comment by mist64** [comment]
Can you paste the output of "sysctl kern.hv_support"? It is supposed to be "1", otherwise your hardware does not support it...

**Comment by ghost** [comment]
Yes it's "1".
My hardware: MacBook Pro Retina 2012. Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz

**Comment by ghost** [comment]
I should run it with root. Thanks. Solved.

FYI (lldb's output to see segfault's cause):
Process 14376 launched: './hvdos' (x86_64)
Process 14376 stopped
- thread #1: tid = 0x726d7, 0x00007fff8df4ae27 libsystem_c.dylib`flockfile + 4, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x68)
  frame #0: 0x00007fff8df4ae27 libsystem_c.dylib`flockfile + 4
  libsystem_c.dylib`flockfile + 4:
  -> 0x7fff8df4ae27:  movq   0x68(%rdi), %rdi
  0x7fff8df4ae2b:  addq   $0x8, %rdi
  0x7fff8df4ae2f:  popq   %rbp
  0x7fff8df4ae30:  jmp    0x7fff8df9382c            ; symbol stub for: pthread_mutex_lock

**Comment by mist64** [comment]
Oh, seems like you ran it without arguments. I made it print a "Usage" line when run without arguments, so this should be fixed. hvdos should not require root.

**Comment by ghost** [comment]
Thanks
